# Generated by Django 5.2.8 on 2025-11-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, '普通用户'), (0, '管理员')], default=0, verbose_name='用户角色'),
        ),
    ]
