"""
Django settings for tianfu_oa project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


load_dotenv()  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-xj9@7=15)r%7h9&94w18ljv-m+ytejirbvk(d4ra93!%yl%g+-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 开发环境开启调试，生产环境需改为False

# 允许访问的域名（开发环境允许本地访问）
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方APP（接口开发用）
    'rest_framework',
    # 自定义APP（自己写的功能模块）
    'apps.user',
    'apps.approval',
    'apps.notice',
    'apps.department',
    'drf_yasg',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
]


ROOT_URLCONF = 'tianfu_oa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 配置模板目录（指向项目根目录的templates文件夹）
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tianfu_oa.wsgi.application'


# Database
# 替换默认的SQLite为MySQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL引擎
        'NAME': os.getenv('DB_NAME', 'tianfu_oa'),  # 数据库名（需提前在MySQL中创建）
        'USER': os.getenv('DB_USER', 'root'),  # MySQL用户名
        'PASSWORD': os.getenv('DB_PASSWORD', '123456'),  # MySQL密码（替换为你的实际密码）
        'HOST': os.getenv('DB_HOST', 'localhost'),  # 数据库地址（本地为localhost）
        'PORT': os.getenv('DB_PORT', '3306'),  # 数据库端口（默认3306）
        'OPTIONS': {'charset': 'utf8mb4'},  # 支持emoji等特殊字符
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# 配置中文和北京时间
LANGUAGE_CODE = 'zh-hans'  # 中文
TIME_ZONE = 'Asia/Shanghai'  # 北京时间
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# 配置静态文件目录（指向项目根目录的static文件夹）
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # 每页条数，可自定义
}