# Generated by Django 5.2.8 on 2025-11-25 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='审批类型名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '审批类型',
                'verbose_name_plural': '审批类型',
                'db_table': 'tb_approval_type',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='审批单标题')),
                ('content', models.TextField(verbose_name='审批内容')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '待审批'), (2, '已通过'), (3, '已驳回')], default=0, verbose_name='审批状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaltype', verbose_name='审批类型')),
            ],
            options={
                'verbose_name': '审批单',
                'verbose_name_plural': '审批单',
                'db_table': 'tb_approval',
            },
        ),
    ]
