# Generated by Django 5.2.8 on 2025-11-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltype',
            name='reject_remark',
            field=models.TextField(blank=True, null=True, verbose_name='驳回备注'),
        ),
    ]
